{% set python_min = "3.10" %}
{% set name = "cerberecontrib-s3" %}
{% set version = "3.1.2" %}

package: 
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.ifremer.fr/cerbere/cerberecontrib-s3/-/archive/{{ version }}/cerberecontrib-s3-{{ version }}.tar.gz
  sha256: ed0bc1f116f90572c138df0a6f4c8ebefeb78cfca2682f9f04c80652b75c0c5d
  
build:
  noarch: python
  script_env:
    - POETRY_DYNAMIC_VERSIONING_BYPASS={{ version }}
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning >=1.0.0,<2.0.0
    - pip
  run:
    - python {{ python_min }}
    - lxml >=4,<5
    - more-itertools >=9.1,<10.0.0
    - attrs >=24.2.0,<25.1.0
    - h5netcdf >=1.3.0
    - cerbere >=3.1.2,<4.0.0
    - cerberecontrib-ghrsst >=3.1.2,<4.0.0
 
test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - cerberecontrib_s3
    
about:
  home: https://gitlab.ifremer.fr/cerbere/cerberecontrib-s3
  license: LGPL-3.0-only
  license_file: LICENSE.md
  summary: Companion package of cerbere for Copernicus Sentinel-3 products.
  doc_url: https://cerbere.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - erwanbodere
    - criou-cg
    - cso2943
    - Marie59
    - jfpiolle
